
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=${DEV}
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DEV=${DEV}
      - TZ=${TZ}
      - FAKE_FILE_WORKING=${FAKE_FILE_WORKING}
    volumes:
      - ${APP_PATH}:/app
      - ${DATA_PATH}:/data
